version: '3.7'

services:
  learnocaml:
    container_name: backend
    image: ocamlsf/learn-ocaml:0.13
    ports:
      - '8080:8080'
    environment:
      # (ocaml variable) <container_name>.<network_name>:
      FROM_DOMAIN: "backend.localdomain"
      # (alpine msmtp variable) hostname of the SMTP server:
      SMTPSERVER: "postfix"
    env_file:
      - reply-to.env
    depends_on:
      - postfix
    volumes:
      - ${LEARNOCAML_REPO}:/repository:ro
      - learn-ocaml-sync:/sync
    networks:
      - learnocaml-net
    restart: unless-stopped
    networks:
      - learnocaml-net
    logging:
      driver: "journald"

  postfix:
    container_name: postfix
    image: juanluisbaptiste/postfix
    environment:
      ALWAYS_ADD_MISSING_HEADERS: "yes"
      # (postfix variable) DNS of myself, the server sending mails:
      SERVER_HOSTNAME: "mail.localdomain"
      # (postfix variable) remote MTA credentials:
      SMTP_PASSWORD_FILE: "/secrets/smtp_password"
    env_file:
      - smtp.env
    volumes:
      - "./secrets:/secrets"
    networks:
      - learnocaml-net
    logging:
      driver: "journald"

volumes:
  learn-ocaml-sync:
    driver: local

networks:
  learnocaml-net:
    driver: bridge
    name: localdomain

# @ https://docs.docker.com/config/containers/logging/configure/
# @ https://docs.docker.com/config/containers/logging/journald/
# % docker logs backend
# % journalctl CONTAINER_NAME=backend
