version: '3.7'

services:
  https-portal:
    image: steveltn/https-portal:1.12.0
    container_name: https-portal
    volumes:
      - https-portal-certs:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment:
      DOMAINS: '${LEARNOCAML_DOMAIN} -> http://learnocaml:8080'
      # TODO => uncomment next line after a successful deployment test
      # STAGE: 'production'
      NUMBITS: '4096'
      ACCESS_LOG: 'stdout'
      ERROR_LOG: 'stderr'
    networks:
      - learnocaml-net
    depends_on:
      - learnocaml
    logging:
      driver: "journald"

  learnocaml:
    container_name: backend
    # image: ocamlsf/learn-ocaml:0.13
    image: pfitaxel/learn-ocaml:staging
    environment:
      # (ocaml variable) <container_name>.<network_name>:
      FROM_DOMAIN: "backend.localdomain"
      # (alpine msmtp variable) hostname of the SMTP server:
      SMTPSERVER: "postfix"
    env_file:
      - root-url.env
      - reply-to.env
    depends_on:
      - postfix
    volumes:
      - ${LEARNOCAML_REPO}:/repository:ro
      - learn-ocaml-sync:/sync
    networks:
      - learnocaml-net
    restart: unless-stopped
    networks:
      - learnocaml-net
    logging:
      driver: "journald"

  postfix:
    container_name: postfix
    image: juanluisbaptiste/postfix
    environment:
      ALWAYS_ADD_MISSING_HEADERS: "yes"
      # (postfix variable) DNS of myself, the server sending mails:
      SERVER_HOSTNAME: "mail.localdomain"
      # (postfix variable) remote MTA credentials:
      SMTP_PASSWORD_FILE: "/secrets/smtp_password"
    env_file:
      - smtp.env
    volumes:
      - "./secrets:/secrets"
    networks:
      - learnocaml-net
    logging:
      driver: "journald"

volumes:
  learn-ocaml-sync:
    driver: local
  https-portal-certs:
    driver: local

networks:
  learnocaml-net:
    driver: bridge
    name: localdomain

# @ https://docs.docker.com/config/containers/logging/configure/
# @ https://docs.docker.com/config/containers/logging/journald/
# @ https://github.com/SteveLTN/https-portal#quick-start
# % docker logs https-portal
# % journalctl CONTAINER_NAME=https-portal
# % docker logs backend
# % journalctl CONTAINER_NAME=backend
